language: csharp
dotnet: 2.1.300-preview2-008533
mono: latest
os:
  - linux
  - osx

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master

cache:
  bundler: true
  directories:
  - ./packages
  - /.dotnetcli
  - $HOME/Library/Caches/Homebrew

before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - git config --global core.autocrlf input
  - chmod +x ./build.sh
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

script:
  - ./build.sh

